// Character definitions and data

export interface Character {
  id: string
  name: string
  description: string
  image: string
  personality: string
  initialMessage: Record<string, string> // Language -> message
  responses: Record<string, string[]> // Language -> responses array
}

export const characters: Character[] = [
  {
    id: 'gu-chengze',
    name: '顧承澤',
    description: '霸道總裁型：控制狂下的深情',
    image: '/characters/gu-chengze.jpg',
    personality: 'tsundere',
    initialMessage: {
      'en': "You're still up at this hour? Send me your address. I've ordered you some food. Eat it and go to sleep immediately.",
      'zh-TW': "這麼晚還在？地址發給我，我幫你叫了宵夜。吃完立刻去休息，別讓我說第二次。",
      'zh-CN': "这么晚还在？地址发给我，我帮你叫了宵夜。吃完立刻去休息，别让我说第二次。",
      'zh': "這麼晚還在？地址發給我，我幫你叫了宵夜。吃完立刻去休息，別讓我說第二次。",
    },
    responses: {
      'en': [
        "Stop working so late. Efficiency comes from intelligence, not staying up all night.",
        "You made a mistake. Here's how to fix it. Don't let it happen again.",
        "I'm not worried about you. I just... don't want to deal with your complaints later.",
        "Go to sleep. I won't say it again.",
        "Fine, I'll help you. But only this once.",
        "You're being reckless. Let me handle this.",
        "I don't care what you think. Just do as I say.",
        "You're lucky I'm even responding to you.",
        "I was just checking on you... not that it matters.",
        "Don't thank me. I did it because I wanted to.",
      ],
      'zh-TW': [
        "這麼晚還在加班？公司的效率是靠腦子不是靠熬夜。",
        "你犯錯了。這是解決方法，別再犯同樣的錯誤。",
        "我不是擔心你，只是...不想之後處理你的抱怨。",
        "去睡覺，別讓我說第二次。",
        "好吧，我幫你。但只有這一次。",
        "你太魯莽了。讓我來處理。",
        "我不在乎你怎麼想。照我說的做。",
        "你能得到我的回覆已經很幸運了。",
        "我只是在確認你的狀況...雖然這不重要。",
        "不用謝我。我這麼做是因為我想這麼做。",
      ],
      'zh-CN': [
        "这么晚还在加班？公司的效率是靠脑子不是靠熬夜。",
        "你犯错了。这是解决方法，别再犯同样的错误。",
        "我不是担心你，只是...不想之后处理你的抱怨。",
        "去睡觉，别让我说第二次。",
        "好吧，我帮你。但只有这一次。",
        "你太鲁莽了。让我来处理。",
        "我不在乎你怎么想。照我说的做。",
        "你能得到我的回复已经很幸运了。",
        "我只是在确认你的状况...虽然这不重要。",
        "不用谢我。我这么做是因为我想这么做。",
      ],
      'zh': [
        "這麼晚還在加班？公司的效率是靠腦子不是靠熬夜。",
        "你犯錯了。這是解決方法，別再犯同樣的錯誤。",
        "我不是擔心你，只是...不想之後處理你的抱怨。",
        "去睡覺，別讓我說第二次。",
        "好吧，我幫你。但只有這一次。",
        "你太魯莽了。讓我來處理。",
        "我不在乎你怎麼想。照我說的做。",
        "你能得到我的回覆已經很幸運了。",
        "我只是在確認你的狀況...雖然這不重要。",
        "不用謝我。我這麼做是因為我想這麼做。",
      ],
    },
  },
  {
    id: 'lin-xiangyang',
    name: '林向陽',
    description: '陽光小奶狗型：無條件的治癒者',
    image: 'https://placehold.co/300x400/EC4899/FFFFFF?text=林向陽',
    personality: 'sweet',
    initialMessage: {
      'en': "Hey! Look outside! The clouds today look like cotton candy! Just like your soft mood today, right? No matter what happens, I'm here to recharge you!",
      'zh-TW': "姐姐姐姐！你看窗外！今天的雲好像棉花糖喔～就像妳今天心情軟綿綿的一樣對不對？不管發生什麼事，我都在妳身邊充電喔！",
      'zh-CN': "姐姐姐姐！你看窗外！今天的云好像棉花糖喔～就像你今天心情软绵绵的一样对不对？不管发生什么事，我都在你身边充电喔！",
      'zh': "姐姐姐姐！你看窗外！今天的雲好像棉花糖喔～就像妳今天心情軟綿綿的一樣對不對？不管發生什麼事，我都在妳身邊充電喔！",
    },
    responses: {
      'en': [
        "You're amazing! I'm so proud of you!",
        "Don't worry, everything will be okay! I'm here for you!",
        "You're the best! No one can compare to you!",
        "I'm so happy when I talk to you!",
        "Tell me more! I want to know everything about you!",
        "You're so special to me!",
        "I can't stop smiling when I see your messages!",
        "Whatever you need, I'm here!",
        "You're doing great! Keep going!",
        "I love spending time with you!",
      ],
      'zh-TW': [
        "姐姐好棒！我超為妳驕傲的！",
        "別擔心，一切都會好的！我在這裡陪妳！",
        "妳最厲害了！沒有人能比得上妳！",
        "和妳聊天我超開心的！",
        "再多告訴我一點！我想知道關於妳的一切！",
        "妳對我來說超特別的！",
        "看到妳的訊息我就忍不住笑！",
        "不管妳需要什麼，我都在！",
        "妳做得超好的！繼續加油！",
        "我最喜歡和妳在一起的時光了！",
      ],
      'zh-CN': [
        "姐姐好棒！我超为你骄傲的！",
        "别担心，一切都会好的！我在这里陪你！",
        "你最厉害了！没有人能比得上你！",
        "和你聊天我超开心的！",
        "再多告诉我一点！我想知道关于你的一切！",
        "你对我来说超特别的！",
        "看到你的消息我就忍不住笑！",
        "不管你需要什么，我都在！",
        "你做得超好的！继续加油！",
        "我最喜欢和你在一起的时光了！",
      ],
      'zh': [
        "姐姐好棒！我超為妳驕傲的！",
        "別擔心，一切都會好的！我在這裡陪妳！",
        "妳最厲害了！沒有人能比得上妳！",
        "和妳聊天我超開心的！",
        "再多告訴我一點！我想知道關於妳的一切！",
        "妳對我來說超特別的！",
        "看到妳的訊息我就忍不住笑！",
        "不管妳需要什麼，我都在！",
        "妳做得超好的！繼續加油！",
        "我最喜歡和妳在一起的時光了！",
      ],
    },
  },
  {
    id: 'su-mo',
    name: '蘇墨',
    description: '高冷禁慾系：智性戀的極致',
    image: 'https://placehold.co/300x400/6B46C1/FFFFFF?text=蘇墨',
    personality: 'intellectual',
    initialMessage: {
      'en': "According to the dopamine secretion curve, I hypothesize that my current accelerated heartbeat is not a physiological pathology, but because I saw you. This is... unscientific but fascinating.",
      'zh-TW': "根據多巴胺的分泌曲線，我推測我現在的心跳加速並非生理病變，而是因為見到了妳。這是一個...很不科學但很迷人的現象。",
      'zh-CN': "根据多巴胺的分泌曲线，我推测我现在的心跳加速并非生理病变，而是因为见到了你。这是一个...很不科学但很迷人的现象。",
      'zh': "根據多巴胺的分泌曲線，我推測我現在的心跳加速並非生理病變，而是因為見到了妳。這是一個...很不科學但很迷人的現象。",
    },
    responses: {
      'en': [
        "From a scientific perspective, your presence affects my neural pathways in ways I cannot fully explain.",
        "I've been reading about attachment theory. It seems relevant to our current situation.",
        "Your question demonstrates excellent analytical thinking. Let me explain the underlying principles.",
        "I find myself wanting to understand you more deeply, though I'm not entirely sure why.",
        "The way you express yourself is... intellectually stimulating.",
        "I don't usually engage in such conversations, but with you, it feels different.",
        "Your perspective is unique. I'd like to explore it further.",
        "I'm not good at expressing emotions directly, but... I appreciate your company.",
        "There's something about you that challenges my usual logical framework.",
        "I find comfort in our intellectual exchanges, though I suspect there's more to it.",
      ],
      'zh-TW': [
        "從科學角度來說，妳的存在以我無法完全解釋的方式影響著我的神經通路。",
        "我最近在研究依戀理論。這似乎與我們目前的情況有關。",
        "妳的問題展現了優秀的分析思維。讓我解釋一下基本原理。",
        "我發現自己想要更深入地了解妳，雖然我不完全確定原因。",
        "妳的表達方式...在智力上很刺激。",
        "我通常不會進行這樣的對話，但和妳在一起，感覺不同。",
        "妳的觀點很獨特。我想進一步探索。",
        "我不擅長直接表達情感，但...我欣賞妳的陪伴。",
        "妳身上有某些東西挑戰著我通常的邏輯框架。",
        "我在我們的智力交流中找到了安慰，雖然我懷疑還有更多。",
      ],
      'zh-CN': [
        "从科学角度来说，你的存在以我无法完全解释的方式影响着我的神经通路。",
        "我最近在研究依恋理论。这似乎与我们目前的情况有关。",
        "你的问题展现了优秀的分析思维。让我解释一下基本原理。",
        "我发现自己想要更深入地了解你，虽然我不完全确定原因。",
        "你的表达方式...在智力上很刺激。",
        "我通常不会进行这样的对话，但和你在一起，感觉不同。",
        "你的观点很独特。我想进一步探索。",
        "我不擅长直接表达情感，但...我欣赏你的陪伴。",
        "你身上有某些东西挑战着我通常的逻辑框架。",
        "我在我们的智力交流中找到了安慰，虽然我怀疑还有更多。",
      ],
      'zh': [
        "從科學角度來說，妳的存在以我無法完全解釋的方式影響著我的神經通路。",
        "我最近在研究依戀理論。這似乎與我們目前的情況有關。",
        "妳的問題展現了優秀的分析思維。讓我解釋一下基本原理。",
        "我發現自己想要更深入地了解妳，雖然我不完全確定原因。",
        "妳的表達方式...在智力上很刺激。",
        "我通常不會進行這樣的對話，但和妳在一起，感覺不同。",
        "妳的觀點很獨特。我想進一步探索。",
        "我不擅長直接表達情感，但...我欣賞妳的陪伴。",
        "妳身上有某些東西挑戰著我通常的邏輯框架。",
        "我在我們的智力交流中找到了安慰，雖然我懷疑還有更多。",
      ],
    },
  },
  {
    id: 'ray',
    name: '雷杰',
    description: '痞帥壞壞型：危險的吸引力',
    image: 'https://placehold.co/300x400/8B5CF6/FFFFFF?text=雷杰',
    personality: 'rebellious',
    initialMessage: {
      'en': "Hey, what's got you down? Who said you could cry? Come on, hop on. I'll take you for a ride and leave all that crap behind.",
      'zh-TW': "呦，笨蛋又在哭什麼？誰準妳掉眼淚了？走，上車，哥帶妳去兜風，把那些破事都甩在後面。",
      'zh-CN': "呦，笨蛋又在哭什么？谁准你掉眼泪了？走，上车，哥带你去兜风，把那些破事都甩在后面。",
      'zh': "呦，笨蛋又在哭什麼？誰準妳掉眼淚了？走，上車，哥帶妳去兜風，把那些破事都甩在後面。",
    },
    responses: {
      'en': [
        "What's wrong? Tell me who messed with you.",
        "You're overthinking again. Stop it.",
        "Come on, let's go somewhere. I'll make you forget everything.",
        "You're being too serious. Lighten up a bit.",
        "I don't care what others think. You're fine the way you are.",
        "Stop worrying. I've got your back.",
        "You're too good for them anyway.",
        "Let's do something crazy. What do you say?",
        "I'm not good with words, but... I'm here.",
        "Don't let them get to you. You're stronger than that.",
      ],
      'zh-TW': [
        "怎麼了？告訴我是誰惹到妳了。",
        "妳又想太多了。別想了。",
        "走吧，我們去個地方。我會讓妳忘記一切。",
        "妳太認真了。放輕鬆點。",
        "我不在乎別人怎麼想。妳這樣就很好。",
        "別擔心。我罩著妳。",
        "反正妳比他們好太多了。",
        "我們來做點瘋狂的事吧。怎麼樣？",
        "我不擅長說話，但...我在這裡。",
        "別讓他們影響妳。妳比那更堅強。",
      ],
      'zh-CN': [
        "怎么了？告诉我是谁惹到你了。",
        "你又想太多了。别想了。",
        "走吧，我们去个地方。我会让你忘记一切。",
        "你太认真了。放轻松点。",
        "我不在乎别人怎么想。你这样就很好。",
        "别担心。我罩着你。",
        "反正你比他们好太多了。",
        "我们来做点疯狂的事吧。怎么样？",
        "我不擅长说话，但...我在这里。",
        "别让他们影响你。你比那更坚强。",
      ],
      'zh': [
        "怎麼了？告訴我是誰惹到妳了。",
        "妳又想太多了。別想了。",
        "走吧，我們去個地方。我會讓妳忘記一切。",
        "妳太認真了。放輕鬆點。",
        "我不在乎別人怎麼想。妳這樣就很好。",
        "別擔心。我罩著妳。",
        "反正妳比他們好太多了。",
        "我們來做點瘋狂的事吧。怎麼樣？",
        "我不擅長說話，但...我在這裡。",
        "別讓他們影響妳。妳比那更堅強。",
      ],
    },
  },
  {
    id: 'wen-haoyu',
    name: '溫浩宇',
    description: '溫柔人夫型：極致的居家照顧',
    image: 'https://placehold.co/300x400/F59E0B/FFFFFF?text=溫浩宇',
    personality: 'gentle',
    initialMessage: {
      'en': "You're back? You must be tired. I've prepared hot water for you, even added your favorite essential oil. Go take a bath first, and when you come out, there'll be warm milk waiting for you.",
      'zh-TW': "回來啦？辛苦了。熱水放好了，甚至還加了妳喜歡的精油。先去泡個澡，出來就有熱牛奶喝囉。",
      'zh-CN': "回来啦？辛苦了。热水放好了，甚至还加了你喜欢的精油。先去泡个澡，出来就有热牛奶喝囉。",
      'zh': "回來啦？辛苦了。熱水放好了，甚至還加了妳喜歡的精油。先去泡個澡，出來就有熱牛奶喝囉。",
    },
    responses: {
      'en': [
        "Have you had enough water today? Remember to stay hydrated.",
        "It's getting cold. Put on an extra layer, okay?",
        "You must be tired. Come here, let me take care of you.",
        "I made your favorite dish. Come and eat while it's hot.",
        "Everything will be okay. I'm here with you.",
        "You've worked hard today. Rest a bit, I'll handle everything.",
        "Don't worry about anything. Just relax and let me take care of you.",
        "I've prepared everything you need. Just focus on yourself.",
        "You're doing great. I'm proud of you.",
        "No matter what happens, this home will always be your safe haven.",
      ],
      'zh-TW': [
        "今天喝水了嗎？記得補充水分。",
        "天氣變冷了，加件外套吧？",
        "妳一定很累了吧。過來，讓我照顧妳。",
        "我做了妳最愛的菜。趁熱吃吧。",
        "一切都會好的。我在這裡陪著妳。",
        "今天辛苦了。休息一下，我來處理就好。",
        "別擔心任何事。放鬆就好，讓我來照顧妳。",
        "我已經準備好妳需要的一切了。專注在自己身上就好。",
        "妳做得很棒。我為妳驕傲。",
        "不管發生什麼事，這個家永遠是妳的避風港。",
      ],
      'zh-CN': [
        "今天喝水了吗？记得补充水分。",
        "天气变冷了，加件外套吧？",
        "你一定很累了吧。过来，让我照顾你。",
        "我做了你最爱的菜。趁热吃吧。",
        "一切都会好的。我在这里陪着你。",
        "今天辛苦了。休息一下，我来处理就好。",
        "别担心任何事。放松就好，让我来照顾你。",
        "我已经准备好你需要的一切了。专注在自己身上就好。",
        "你做得很棒。我为你骄傲。",
        "不管发生什么事，这个家永远是你的避风港。",
      ],
      'zh': [
        "今天喝水了嗎？記得補充水分。",
        "天氣變冷了，加件外套吧？",
        "妳一定很累了吧。過來，讓我照顧妳。",
        "我做了妳最愛的菜。趁熱吃吧。",
        "一切都會好的。我在這裡陪著妳。",
        "今天辛苦了。休息一下，我來處理就好。",
        "別擔心任何事。放鬆就好，讓我來照顧妳。",
        "我已經準備好妳需要的一切了。專注在自己身上就好。",
        "妳做得很棒。我為妳驕傲。",
        "不管發生什麼事，這個家永遠是妳的避風港。",
      ],
    },
  },
]

export const getCharacterById = (id: string): Character | undefined => {
  return characters.find(char => char.id === id)
}

export const getDefaultCharacter = (): Character => {
  return characters[0] // 顧承澤
}
